system:                                       #系统配置
  sys: mac                                    #操作系统[win、mac、linux]
xray:                                         #xray配置信息
  name: xray_darwin_amd64                     #xray程序名称 注:win操作系统需要exe后缀名
  proxy: 127.0.0.1:8888                       #代理端口配置
rad:                                          #rad配置信息
  name: rad_darwin_amd64                      #rad程序名称 注:win操作系统需要exe后缀名
  chrome:                                     #chrome浏览器路径 注：rad报错时可配置
parse:                                        #默认解析配置
  header:                                     #需要解析的header请求，可按照格式新增其他header
    - Host
    - Cookie
    - User-Agent